image: node:latest

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - apt-get update -qy
    - cd functions
    - apt-get install -yqq jq
    - export APP_NAME=$(cat package.json | jq -r .deployment)
    - echo "Deployment name - ${APP_NAME}"
    - npm install -g firebase-tools
    - npm install
    - cd ..
    - echo $APP_NAME
    - firebase use --token $DEPLOY_KEY $APP_NAME
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $DEPLOY_KEY  --project $APP_NAME
